[2023-10-14T05:18:02.435+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: titanic.read_db scheduled__2023-10-14T05:17:00+00:00 [queued]>
[2023-10-14T05:18:02.443+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: titanic.read_db scheduled__2023-10-14T05:17:00+00:00 [queued]>
[2023-10-14T05:18:02.444+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-10-14T05:18:02.457+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): read_db> on 2023-10-14 05:17:00+00:00
[2023-10-14T05:18:02.462+0000] {standard_task_runner.py:57} INFO - Started process 3184 to run task
[2023-10-14T05:18:02.464+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'titanic', 'read_db', 'scheduled__2023-10-14T05:17:00+00:00', '--job-id', '456', '--raw', '--subdir', 'DAGS_FOLDER/titanic01.py', '--cfg-path', '/tmp/tmp7sz8098j']
[2023-10-14T05:18:02.467+0000] {standard_task_runner.py:85} INFO - Job 456: Subtask read_db
[2023-10-14T05:18:02.515+0000] {task_command.py:415} INFO - Running <TaskInstance: titanic.read_db scheduled__2023-10-14T05:17:00+00:00 [running]> on host 89ffa62682cc
[2023-10-14T05:18:02.745+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='titanic' AIRFLOW_CTX_TASK_ID='read_db' AIRFLOW_CTX_EXECUTION_DATE='2023-10-14T05:17:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-14T05:17:00+00:00'
[2023-10-14T05:18:02.772+0000] {base.py:73} INFO - Using connection ID 'mydb' for task execution.
[2023-10-14T05:18:03.407+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-10-14T05:18:03.414+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=titanic, task_id=read_db, execution_date=20231014T051700, start_date=20231014T051802, end_date=20231014T051803
[2023-10-14T05:18:03.440+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-14T05:18:03.455+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
